In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_excel('../data/training.xlsx')
df_test = pd.read_excel('../data/test-Ans.xlsx')

### 数据预处理

In [10]:
list_columns = df_train['Product_Category'].unique()
list_columns

array(['科技用品', '出版品/影音', '运动/户外', '家用电器', '饮食食品', '保健卫生', '包包/提袋/卡套',
       '衣着服饰', '汽/机车周边', '居家生活用品', '亲子儿童', '文具卡片', '鞋履袜品', '保养美妆',
       '软件/系统/服务', '餐厨用品', '休闲/乐器', '修缮园艺', '宠物用品', '艺术/收藏品/模型', '配件饰品',
       'DIY 工具', '宗教/风水', '其他'], dtype=object)

In [11]:
list_nums = np.arange(len(df_train['Product_Category'].unique()))
list_nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
cate_dict = dict()

for key,value in zip(list_columns, list_nums):
    cate_dict.update({key:value})
    
cate_dict

{'科技用品': 0,
 '出版品/影音': 1,
 '运动/户外': 2,
 '家用电器': 3,
 '饮食食品': 4,
 '保健卫生': 5,
 '包包/提袋/卡套': 6,
 '衣着服饰': 7,
 '汽/机车周边': 8,
 '居家生活用品': 9,
 '亲子儿童': 10,
 '文具卡片': 11,
 '鞋履袜品': 12,
 '保养美妆': 13,
 '软件/系统/服务': 14,
 '餐厨用品': 15,
 '休闲/乐器': 16,
 '修缮园艺': 17,
 '宠物用品': 18,
 '艺术/收藏品/模型': 19,
 '配件饰品': 20,
 'DIY 工具': 21,
 '宗教/风水': 22,
 '其他': 23}

In [14]:
num_dict = dict()

for key,value in zip(list_nums, list_columns):
    num_dict.update({key:value})
    
num_dict

{0: '科技用品',
 1: '出版品/影音',
 2: '运动/户外',
 3: '家用电器',
 4: '饮食食品',
 5: '保健卫生',
 6: '包包/提袋/卡套',
 7: '衣着服饰',
 8: '汽/机车周边',
 9: '居家生活用品',
 10: '亲子儿童',
 11: '文具卡片',
 12: '鞋履袜品',
 13: '保养美妆',
 14: '软件/系统/服务',
 15: '餐厨用品',
 16: '休闲/乐器',
 17: '修缮园艺',
 18: '宠物用品',
 19: '艺术/收藏品/模型',
 20: '配件饰品',
 21: 'DIY 工具',
 22: '宗教/风水',
 23: '其他'}

In [15]:
df_train['target'] = df_train['Product_Category'].apply(lambda x :cate_dict.get(x))
df_train.head(5)

,Product_ID,Product_Category,Product_Description,target
0,4085,科技用品,耳机线又打结了吗? 常找不到保护盒吗? \n使用束线板，让您的耳机线从此乖乖听话不打结!!,0
1,2168,出版品/影音,一位思觉失调患者从低谷爬上来的血泪小说，期望能用出书让更多人认识思觉失调症，做出微薄的贡献,1
2,320,运动/户外,一个钢绳锁，搞定旅行所有的安全需求，旅行安全第一选择，不论是锁行李箱，置物柜，火车行李架，甚...,2
3,79,家用电器,3秒即热，这不是魔术\n✅3秒即热\n✅4档水量设定\n✅5档快捷水温\n✅无段式水量设置\...,3
4,3965,运动/户外,踏板就是功率计与踏频计，无需校正，安装超Easy，一组可交替多车使用。透过车表或手机让你随时...,2

In [16]:
df_test['target'] = df_test['Product_Category'].apply(lambda x :cate_dict.get(x))
df_test.head(5)

,Product_ID,Product_Category,Product_Description,target
0,1142,出版品/影音,传统书法用具携带不便、清洗麻烦、收纳不易、习字缓慢等问题，【临真LIN JEN】创新设计全方...,1
1,764,休闲/乐器,《怪兽来了！》是一款寓教于乐的桌游，既好玩又能学情绪！希望透过游戏带领孩子更认识情绪吗？一起...,16
2,75,居家生活用品,我们发现市面上枕头百百种，有羽绒枕、有记忆枕、 有乳胶枕，但为什么还是无法解决人类失眠的痛苦...,9
3,1308,休闲/乐器,5-99岁都能立刻学会自弹自唱的触控吉他，可以在玩乐中养成孩子勇于表现的自信，又能简单学习音乐！,16
4,2383,科技用品,常忘了您的钥匙吗？有了LINQtoU防丢器，你不会再忘记了！将LINQtoU防丢器当成钥匙圜...,0

In [19]:
sum(df_train['Product_Description'].isna())

3

In [20]:
df_train['Product_Description']=df_train['Product_Description'].fillna('')
df_test['Product_Description']=df_test['Product_Description'].fillna('')

### 加载停用词

In [ ]:
stopwords = set()

with open('stopwords.txt','r',encoding='utf-8') as sw:
    [stopwords.add(line.strip()) for line in sw.readlines()] #list Comprehension
    
stopwords.remove('')
len(stopwords)

### 分词 & 词性标注

In [21]:
import jieba
import jieba.posseg as pseg

def des_clean(s):
    #segs = jieba.cut(s, cut_all=False)
    #print u"[精确模式]: ", "  ".join(segs)
    #分词并标注词性
    segs = pseg.cut(s)
    
    final = ''
    
    for seg ,flag in segs:
        #去停用词
        if seg not in stopwords:
           #去数词和去字符串
           if flag !='m' and flag != 'x' and flag != 'ul':
                #输出分词
                final +=' '+ seg
    return final

In [22]:
df_train['Product_Description'].iloc[0], des_clean(df_train['Product_Description'].iloc[0])

Building prefix dict from the default dictionary ...
Loading model from cache C:/Users/user\AppData\Local\Temp\jieba.cache
Loading model cost 0.719 seconds.
Prefix dict has been built successfully.

('耳机线又打结了吗? 常找不到保护盒吗? \n使用束线板，让您的耳机线从此乖乖听话不打结!!',
 ' 耳机线 打结 找 不到 保护 盒 束 线板 耳机线 乖乖 听话 打结')

In [23]:
df_train['Product_Description_clean']=df_train['Product_Description'].apply(lambda x :des_clean(x))
df_test['Product_Description_clean']=df_test['Product_Description'].apply(lambda x :des_clean(x))

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_train.Product_Description_clean, df_train.target, test_size=0.25, random_state=33)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(sublinear_tf=True, decode_error='ignore')
x_train = tv.fit_transform(X_train)
x_test = tv.transform(X_test)

x_train.shape, x_test.shape

((2506, 12922), (836, 12922))

### 建模

### 1. 朴素贝叶斯

In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
MNB_params = {'alpha':[0.02,0.05, 0.1,0.5]} #拉普拉斯平滑算子
MNB_grid = GridSearchCV(mnb, MNB_params, cv = 5, verbose = 1, scoring = 'neg_log_loss', n_jobs = -1)
MNB_grid.fit(x_train, y_train)
MNB_grid.best_estimator_

Fitting 5 folds for each of 4 candidates, totalling 20 fits

MultinomialNB(alpha=0.02)

In [30]:
from sklearn.metrics import accuracy_score, f1_score

y_pred = MNB_grid.predict(x_test)

print('Accuracy:', accuracy_score(y_test, y_pred))
print('Micro F1:', f1_score(y_test, y_pred, average='micro'))

Accuracy: 0.5334928229665071
Micro F1: 0.5334928229665071

In [32]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.49      0.72      0.59       111
           1       0.42      0.60      0.49        55
           2       0.45      0.50      0.48        20
           3       0.52      0.45      0.48        31
           4       0.60      0.76      0.67        58
           5       0.51      0.45      0.48        44
           6       0.52      0.57      0.54        51
           7       0.55      0.38      0.44        32
           8       0.50      0.08      0.14        12
           9       0.40      0.52      0.45        69
          10       1.00      0.30      0.46        10
          11       0.55      0.54      0.54        56
          12       0.86      0.35      0.50        17
          13       0.83      0.28      0.42        18
          14       0.46      0.18      0.26        33
          15       0.72      0.61      0.66        56
          16       0.63      0.84      0.72        82
          17       0.00      0.00      0.00         7
          18       0.73      0.36      0.48        22
          19       0.00      0.00      0.00        14
          20       0.55      0.24      0.33        25
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         6
          23       0.00      0.00      0.00         4

    accuracy                           0.53       836
   macro avg       0.47      0.36      0.38       836
weighted avg       0.53      0.53      0.51       836

C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

### 2. 随机森林

In [33]:
from imblearn.over_sampling import SMOTE

sm = SMOTE()

x_new, y_new = sm.fit_resample(x_train, y_train)

In [36]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators = 1000, n_jobs=-1).fit(x_new, y_new)

y_pred = rf.predict(x_test)

print('Accuracy:', accuracy_score(y_test, y_pred))
print('Micro F1:', f1_score(y_test, y_pred, average='micro'))

Accuracy: 0.527511961722488
Micro F1: 0.527511961722488

In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.53      0.67      0.59       111
           1       0.49      0.69      0.58        55
           2       0.56      0.50      0.53        20
           3       0.75      0.48      0.59        31
           4       0.55      0.55      0.55        58
           5       0.81      0.39      0.52        44
           6       0.71      0.47      0.56        51
           7       0.48      0.44      0.46        32
           8       0.78      0.58      0.67        12
           9       0.42      0.48      0.45        69
          10       0.80      0.40      0.53        10
          11       0.58      0.55      0.57        56
          12       0.08      0.41      0.13        17
          13       0.67      0.67      0.67        18
          14       0.41      0.36      0.39        33
          15       0.45      0.41      0.43        56
          16       0.83      0.71      0.76        82
          17       1.00      0.57      0.73         7
          18       0.68      0.59      0.63        22
          19       1.00      0.07      0.13        14
          20       0.85      0.44      0.58        25
          21       0.50      0.33      0.40         3
          22       0.00      0.00      0.00         6
          23       0.00      0.00      0.00         4

    accuracy                           0.53       836
   macro avg       0.58      0.45      0.48       836
weighted avg       0.60      0.53      0.54       836

C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [39]:
rf = RandomForestClassifier(class_weight = 'balanced', n_estimators = 1000, n_jobs = -1).fit(x_train, y_train)

y_pred = rf.predict(x_test)

print('Accuracy:', accuracy_score(y_test, y_pred))
print('Micro F1:', f1_score(y_test, y_pred, average='micro'))

Accuracy: 0.5167464114832536
Micro F1: 0.5167464114832536

In [40]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.49      0.73      0.58       111
           1       0.50      0.67      0.57        55
           2       0.56      0.50      0.53        20
           3       0.74      0.45      0.56        31
           4       0.54      0.50      0.52        58
           5       0.80      0.36      0.50        44
           6       0.71      0.39      0.51        51
           7       0.54      0.44      0.48        32
           8       0.70      0.58      0.64        12
           9       0.37      0.49      0.43        69
          10       0.80      0.40      0.53        10
          11       0.70      0.54      0.61        56
          12       0.08      0.41      0.14        17
          13       0.71      0.67      0.69        18
          14       0.45      0.30      0.36        33
          15       0.43      0.36      0.39        56
          16       0.76      0.72      0.74        82
          17       1.00      0.29      0.44         7
          18       0.71      0.68      0.70        22
          19       1.00      0.07      0.13        14
          20       0.91      0.40      0.56        25
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         6
          23       0.00      0.00      0.00         4

    accuracy                           0.52       836
   macro avg       0.56      0.41      0.44       836
weighted avg       0.59      0.52      0.52       836

C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

### 3. XGBOOST

In [41]:
from xgboost import XGBClassifier

xgb = XGBClassifier(n_estimators=360, max_depth=3, learning_rate=0.1).fit(x_new, y_new)

y_pred = xgb.predict(x_test)

print('Accuracy:', accuracy_score(y_test, y_pred))
print('Micro F1:', f1_score(y_test, y_pred, average='micro'))

Accuracy: 0.5299043062200957
Micro F1: 0.5299043062200957

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.47      0.65      0.54       111
           1       0.55      0.65      0.60        55
           2       0.44      0.60      0.51        20
           3       0.57      0.55      0.56        31
           4       0.56      0.48      0.52        58
           5       0.65      0.45      0.53        44
           6       0.62      0.47      0.53        51
           7       0.56      0.47      0.51        32
           8       0.62      0.42      0.50        12
           9       0.33      0.52      0.41        69
          10       0.71      0.50      0.59        10
          11       0.47      0.52      0.49        56
          12       0.70      0.41      0.52        17
          13       0.73      0.61      0.67        18
          14       0.52      0.39      0.45        33
          15       0.52      0.43      0.47        56
          16       0.69      0.76      0.72        82
          17       1.00      0.14      0.25         7
          18       0.65      0.50      0.56        22
          19       0.33      0.14      0.20        14
          20       0.79      0.44      0.56        25
          21       0.50      0.67      0.57         3
          22       0.00      0.00      0.00         6
          23       0.00      0.00      0.00         4

    accuracy                           0.53       836
   macro avg       0.54      0.45      0.47       836
weighted avg       0.55      0.53      0.53       836

C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

### 产生最终输出结果

In [45]:
X_train = df_train.Product_Description_clean
y_train = df_train.target
X_test = df_test.Product_Description_clean
y_test = df_test.target

In [46]:
tv = TfidfVectorizer(sublinear_tf=True, decode_error='ignore')
x_train = tv.fit_transform(X_train)
x_test = tv.transform(X_test)

x_train.shape, x_test.shape

((3342, 15393), (1114, 15393))

In [47]:
mnb = MultinomialNB()
MNB_params = {'alpha':[0.02,0.05, 0.1,0.5]} #拉普拉斯平滑算子
MNB_grid = GridSearchCV(mnb, MNB_params, cv = 5, verbose = 1, scoring = 'neg_log_loss', n_jobs = -1)
MNB_grid.fit(x_train, y_train)
y_pred = MNB_grid.predict(x_test)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

In [50]:
df_test['label'] = y_pred
df_test.head(5)

,Product_ID,Product_Category,Product_Description,target,Product_Description_clean,label
0,1142,出版品/影音,传统书法用具携带不便、清洗麻烦、收纳不易、习字缓慢等问题，【临真LIN JEN】创新设计全方...,1,传统 书法 用具 携带 不便 清洗 麻烦 收纳 不易 习字 缓慢 临真 LIN JEN 创...,9
1,764,休闲/乐器,《怪兽来了！》是一款寓教于乐的桌游，既好玩又能学情绪！希望透过游戏带领孩子更认识情绪吗？一起...,16,怪兽 寓教于乐 桌游 好玩 学 情绪 希望 透过 游戏 带领 孩子 情绪 探险 打怪 对了,16
2,75,居家生活用品,我们发现市面上枕头百百种，有羽绒枕、有记忆枕、 有乳胶枕，但为什么还是无法解决人类失眠的痛苦...,9,发现 市面上 枕头 百 羽绒 枕 记忆 枕 乳胶 枕 解决 人类 失眠 痛苦 市调 研究 ...,9
3,1308,休闲/乐器,5-99岁都能立刻学会自弹自唱的触控吉他，可以在玩乐中养成孩子勇于表现的自信，又能简单学习音乐！,16,学会 自弹自唱 触控 吉他 玩乐 中 养成 孩子 勇于 表现 自信 简单 学习 音乐,16
4,2383,科技用品,常忘了您的钥匙吗？有了LINQtoU防丢器，你不会再忘记了！将LINQtoU防丢器当成钥匙圜...,0,忘 钥匙 LINQtoU 防 丢 器 忘记 LINQtoU 防 丢 器 当成 钥匙 圜 手...,0

In [51]:
df_test['Predicted_Product_Category'] = df_test['label'].apply(lambda x :num_dict.get(x))
df_test.head(5)

,Product_ID,Product_Category,Product_Description,target,Product_Description_clean,label,Predicted_Product_Category
0,1142,出版品/影音,传统书法用具携带不便、清洗麻烦、收纳不易、习字缓慢等问题，【临真LIN JEN】创新设计全方...,1,传统 书法 用具 携带 不便 清洗 麻烦 收纳 不易 习字 缓慢 临真 LIN JEN 创...,9,居家生活用品
1,764,休闲/乐器,《怪兽来了！》是一款寓教于乐的桌游，既好玩又能学情绪！希望透过游戏带领孩子更认识情绪吗？一起...,16,怪兽 寓教于乐 桌游 好玩 学 情绪 希望 透过 游戏 带领 孩子 情绪 探险 打怪 对了,16,休闲/乐器
2,75,居家生活用品,我们发现市面上枕头百百种，有羽绒枕、有记忆枕、 有乳胶枕，但为什么还是无法解决人类失眠的痛苦...,9,发现 市面上 枕头 百 羽绒 枕 记忆 枕 乳胶 枕 解决 人类 失眠 痛苦 市调 研究 ...,9,居家生活用品
3,1308,休闲/乐器,5-99岁都能立刻学会自弹自唱的触控吉他，可以在玩乐中养成孩子勇于表现的自信，又能简单学习音乐！,16,学会 自弹自唱 触控 吉他 玩乐 中 养成 孩子 勇于 表现 自信 简单 学习 音乐,16,休闲/乐器
4,2383,科技用品,常忘了您的钥匙吗？有了LINQtoU防丢器，你不会再忘记了！将LINQtoU防丢器当成钥匙圜...,0,忘 钥匙 LINQtoU 防 丢 器 忘记 LINQtoU 防 丢 器 当成 钥匙 圜 手...,0,科技用品

In [53]:
df_test[['Product_ID', 'Predicted_Product_Category']].to_csv('Final_Results.csv', encoding='gb18030', index = False)

In [54]:
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Micro F1:', f1_score(y_test, y_pred, average='micro'))

Accuracy: 0.5448833034111311
Micro F1: 0.5448833034111311

In [55]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.58      0.83      0.68       147
           1       0.44      0.54      0.48        83
           2       0.69      0.32      0.44        34
           3       0.68      0.70      0.69        46
           4       0.50      0.54      0.52        68
           5       0.60      0.55      0.57        51
           6       0.54      0.58      0.56        65
           7       0.46      0.44      0.45        41
           8       0.75      0.17      0.27        18
           9       0.37      0.49      0.43        93
          10       0.00      0.00      0.00        11
          11       0.51      0.61      0.55        72
          12       0.56      0.25      0.34        20
          13       0.38      0.13      0.19        23
          14       0.68      0.40      0.51        42
          15       0.61      0.62      0.62        72
          16       0.65      0.71      0.68       122
          17       0.00      0.00      0.00         7
          18       0.56      0.33      0.42        30
          19       0.67      0.27      0.39        22
          20       0.64      0.27      0.38        33
          21       0.00      0.00      0.00         6
          22       1.00      0.25      0.40         4
          23       0.00      0.00      0.00         4

    accuracy                           0.54      1114
   macro avg       0.49      0.38      0.40      1114
weighted avg       0.55      0.54      0.53      1114

C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:/Users/user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))